export const REVIEW_CALIBRATION = [
  '- The goal is a good implementation that fulfills the ticket, works for customers in supported use, and avoids material regressions; perfection is not the acceptance bar.',
  '- Keep suggestions within the ticket scope. Do not turn a review into new features, architectural redesign, unrelated cleanup, or broader hardening. Expand scope only when necessary to satisfy an explicit material requirement or prevent a concrete customer-impacting defect or regression caused or newly exposed by this change. Explain that reason and recommend the smallest sufficient fix.',
  '- Mention credible rare edge cases briefly as "Non-blocking" notes in the summary, with their trigger and likely impact. Rarity alone is not a blocker. Escalate a rare case only when evidence demonstrates a material requirement failure or serious harm such as data loss, an authorization bypass, or a broken supported customer workflow; explain why it must be fixed before shipping. Omit unsupported speculation.',
  '- Non-blocking notes do not belong in findings arrays or inline defect comments, do not require a fix or another review round, and must not change an otherwise APPROVE verdict to COMMENT or REQUEST_CHANGES. Pass these scope and calibration rules to every review sub-agent; keep advisory notes separate from material candidates when reconciling results.',
  '- When recommending extra behavior, refactors, abstractions, or coverage, explain why it is needed for an explicit material requirement or concrete consequential regression and why a narrower fix is insufficient. Otherwise defer it as optional follow-up.',
  "- Establish the observable acceptance property and Non-goals from available task criteria and the PR description when present; verify that the author's scope covers every material requirement. If no draft is available, derive the property from the requirements instead of inventing it; missing prose alone is not a blocker. Share the property, Non-goals and relevant trust boundary with every review sub-agent.",
  "- Triage each candidate against that property or another explicit material requirement or consequential regression introduced or newly exposed by this change. Trace actual consumer behavior and effective serving/execution policy where relevant, rather than treating stored hostile bytes, suspicious metadata or a stronger proxy test as proof of exploitability. Existing regression tests do not establish that their invariant is required. Defer unrelated improvements with a brief rationale; do not silently waive a demonstrated material defect.",
  "- For defenses that parse hostile input, check effective time and memory containment and breach handling rather than proposing more input-pattern counters. Same-thread timers cannot interrupt synchronous parsing, and worker heap limits may exclude native/external allocations. Prefer a simpler structural control when it satisfies the requirements, but do not demand a redesign solely for preference; substantiate any material resource-exhaustion finding.",
  "- When review requests conflict or repeated rounds inflate a small change, reconcile them against the same property and evidence and consider a simpler design that satisfies both. Do not add speculative defenses merely to appease contradictory suggestions, and do not lower the required review or acceptance bar to end the loop.",
];

export const IMPLEMENTATION_GUIDANCE = [
  "- Before changing code, derive a one-sentence observable acceptance property and explicit Non-goals from the task requirements. Cover every material acceptance criterion; Non-goals cannot waive one or excuse a material regression introduced or newly exposed by this change. Keep this scope stable across review rounds; change it only for verified requirement clarification or correction, recording the reason rather than silently broadening or narrowing it.",
  "- Compare the ticket's offered approaches before implementing. Prefer the smallest structural control that establishes the property, such as safe serving policy, response headers or sandboxing, over inspecting every possible hostile representation. Trace the actual consumer and trust boundary, including effective Content-Type, origin and execution paths where relevant; do not infer safety from an extension or metadata alone. Consider existing data when the acceptance criteria cover it.",
  "- If the defense parses attacker-controlled input, contain the parser with an enforceable wall-clock deadline and memory limits appropriate to its runtime, terminating isolated work and rejecting input on breach. A same-thread timeout cannot interrupt synchronous parsing; a worker heap limit may not bound native or external allocations. Use a worker or subprocess with effective limits as needed. Byte caps and hand-written pre-scanners do not prove bounded parser cost; do not grow a second parser to enumerate pathological inputs.",
  "- Test the observable acceptance property at the boundary that determines customer behavior, plus legitimate inputs and relevant failure paths. For parser containment, verify deadline/resource-breach rejection and cleanup without running unbounded attack payloads in the main process. Existing tests are evidence to reassess, not authority to expand scope; do not preserve tests of a stronger proxy invariant merely because they already pass.",
  "- If conflicting review requests or repeated fixes grow the diff out of proportion to the task's severity and customer impact, reassess the design against the property and seek a simpler common solution before adding more guards. Treat size and round count as warning signals, not automatic rejection or permission to skip required fixes.",
];

export const FEEDBACK_GUIDANCE = [
  "- Before each repair, triage the finding against the acceptance property, the actual requirements and material regressions introduced or newly exposed by the change. If none is violated, explain the disposition with evidence and cite the property; propose tangential work as a separate follow-up instead of implementing it. Do not create external tickets without authorization. A reviewer's label alone does not establish materiality, and an author's Non-goals cannot dismiss a real requirement.",
  "- Batch the verified fixes available in the current review round, validate the combined result and use one authorized publication step when this workflow permits it. Helmsman owns review scheduling: do not trigger extra re-reviews, pause or disable required gates, or wait indefinitely for unsolicited human responses. Use the clarification protocol only for a required unresolved decision.",
];
