import type { Clarification, TrustedContact } from './data/clarifications';
import { answerClarification, createClarification, fetchClarifications, fetchTrustedContacts, saveTrustedContact } from './data/clarificationClient';
import { escapeHtml as esc } from './logic/html';
import './clarifications.css';

function status(item: Clarification): string { return item.state.replaceAll('-', ' '); }

export function renderClarifications(items: Clarification[], contacts: TrustedContact[], repo: string | null, error: string | null): string {
  return `<div class="clarification-page"><h1>Clarifications</h1><p>Pending questions keep their run waiting. A trusted contact is a default owner only; it never authorizes external sending.</p>${error ? `<p role="alert">${esc(error)}</p>` : ''}
    <section class="panel"><h2>Ask a question</h2><form class="clarification-create"><label>Run ID<input name="runId" required maxlength="128"></label><label>Question ID<input name="id" required maxlength="128"></label><label>Question<textarea name="prompt" required maxlength="4000"></textarea></label><label><input type="checkbox" name="required" checked> Required</label><label>Owner<select name="owner"><option value="local">Local</option><option value="trusted-contact">Trusted contact default</option></select></label><label>Timeout (optional)<input name="timeoutAt" type="datetime-local"></label><button>Ask</button></form></section>
    <section class="panel"><h2>Trusted contacts</h2><p>Use the Jira account ID to match an assignee or reporter automatically.</p><form class="trusted-contact-form"><label>Name<input name="name" required maxlength="160"></label><label>Jira account ID or address<input name="address" required maxlength="320"></label><label><input name="enabled" type="checkbox" checked> Enabled</label><button>Save contact</button></form><ul>${contacts.map(contact => `<li>${esc(contact.name)} · ${esc(contact.address)} · ${contact.enabled ? 'enabled' : 'disabled'}</li>`).join('') || '<li>No trusted contact configured.</li>'}</ul></section>
    <section class="clarification-list"><h2>${repo ? esc(repo) : 'All galleons'}</h2>${items.map(item => `<article class="panel clarification-card"><strong>${esc(item.question)}</strong><span class="clarification-meta">${esc(item.runId)} · ${item.required ? 'required' : 'optional'} · ${esc(item.owner)} · <span class="clarification-state">${esc(status(item))}</span></span>${item.answer ? `<p>${esc(item.answer)}</p>` : ''}${item.state === 'pending' ? `<form data-answer="${esc(item.id)}"><textarea name="answer" required maxlength="4000" placeholder="Answer"></textarea><button>Answer</button></form>` : ''}</article>`).join('') || '<p>No clarifications in this scope.</p>'}</section></div>`;
}

export function mountClarifications(container: HTMLElement, options: { repo(): string | null }): { refresh(): Promise<void>; destroy(): void } {
  let items: Clarification[] = []; let contacts: TrustedContact[] = []; let error: string | null = null; let destroyed = false; let sequence = 0;
  const paint = () => { if (!destroyed) container.innerHTML = renderClarifications(items, contacts, options.repo(), error); };
  async function refresh(): Promise<void> { const token = ++sequence; const repo = options.repo(); try { const [nextItems, nextContacts] = await Promise.all([fetchClarifications(repo), fetchTrustedContacts()]); if (destroyed || token !== sequence || repo !== options.repo()) return; items = nextItems; contacts = nextContacts; error = null; } catch (reason) { if (!destroyed && token === sequence) error = reason instanceof Error ? reason.message : 'Clarifications are unavailable.'; } paint(); }
  const submit = (event: Event) => { const form = event.target; if (!(form instanceof HTMLFormElement)) return; event.preventDefault(); const data = new FormData(form); const action = async () => { if (form.matches('.clarification-create')) { const local = data.get('timeoutAt'); await createClarification({ runId: String(data.get('runId') ?? ''), id: String(data.get('id') ?? ''), prompt: String(data.get('prompt') ?? ''), required: data.get('required') === 'on', owner: data.get('owner') === 'trusted-contact' ? 'trusted-contact' : 'local', ...(typeof local === 'string' && local ? { timeoutAt: new Date(local).toISOString() } : {}) }); } else if (form.matches('.trusted-contact-form')) { await saveTrustedContact({ name: String(data.get('name') ?? ''), address: String(data.get('address') ?? ''), enabled: data.get('enabled') === 'on' }); } else { const id = form.dataset.answer; if (!id) return; await answerClarification(id, options.repo(), String(data.get('answer') ?? '')); } await refresh(); }; void action().catch(reason => { error = reason instanceof Error ? reason.message : 'Action failed.'; paint(); }); };
  container.addEventListener('submit', submit); paint(); void refresh();
  return { refresh, destroy() { destroyed = true; sequence++; container.removeEventListener('submit', submit); } };
}
